
// This file was auto-generated by ML.NET Model Builder. 

using MLModel4_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel4.ModelInput sampleData = new MLModel4.ModelInput()
{
    Total_score = 7.82F,
    Company_culture = 2.01F,
    Job_satisfaction = 8.49F,
    Professional_growth = 7.96F,
    Manager_relationship = 9.13F,
    Compensation_and_benefits = 9.94F,
    Work_life_balance = 9.37F,
    Satisfy_ = false,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel4.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Reason with predicted Reason from sample data...\n\n");


Console.WriteLine($"Total_score: {7.82F}");
Console.WriteLine($"Reason: {@"Company culture"}");
Console.WriteLine($"Company_culture: {2.01F}");
Console.WriteLine($"Job_satisfaction: {8.49F}");
Console.WriteLine($"Professional_growth: {7.96F}");
Console.WriteLine($"Manager_relationship: {9.13F}");
Console.WriteLine($"Compensation_and_benefits: {9.94F}");
Console.WriteLine($"Work_life_balance: {9.37F}");
Console.WriteLine($"Satisfy_: {false}");


Console.WriteLine($"\n\nPredicted Reason: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

